### ISSUE TITLE
New customer - Doubt about Setting Scales Position

### ISSUE THREAD

**Issue by britolc** [ccoolbaugh/FloWave.US#13]
Hi there,
In this part, Distance Scale Position is only dysplaing for me, neither red or green. So, after in FloWave the following error happen:
Undefined function or variable 'PWy'.
Error in FloWaveUS (line 84)
ROI(:,:,:) = OneFrame(PWy(1):PWy(2), PWx(1):PWx(2),:);

Could you please give some guide here?
Thanks

**Comment by ccoolbaugh** [comment]
Hello,
I am happy to help, but I need more information to determine the source of the error. Could you please tell me the following: 

1. What version of FloWave.US were you using?
2. After downloading FloWave.US, did you test the code using the [demo](https://github.com/ccoolbaugh/FloWave.US/tree/master/Demo) videos?
3. If you run the demo videos, does the error occur?
4. Did you create a custom Ultrasound Screen Capture Settings file (UsSetup.m) prior to running FloWave.US or did you use the default settings file (GELogiqBookeDefault.mat)?

I suspect the error message is related to the Ultrasound Screen Capture Settings file not the "setting the distance scale position". Your responses to my questions should help me resolve the issue. 

Thank you,
Crystal

**Comment by britolc** [comment]
Hi Crystal,

So, let's question by question:

1 - To be honest, I did not get the version, but the propertiers says it
was created in 02/01/2017, and I downloaded from github two weeks ago;

2 - Yes, I dd.

3 - Yes, It occured.

4 - I made both, but, when I created custom settings, the scale for
distance (yellow) was only showed up.

Sorry if I was not more clear in my explanations, this is may first time
using a software to analyze ultrasound images.


Our lab inted to start using FloWaveUS so I'm the responsible to figure out
how it works

Thank you so much for your time
Best wishes

Leandro










2017-03-21 12:33 GMT-03:00 Crystal Coolbaugh <notifications@github.com>:

**Comment by ccoolbaugh** [comment]
Hi Leandro,
Addressing errors with software remotely can be a challenge so working through problems one-by-one is often best, and I appreciate your patience responding to my questions to resolve your error. 

Building off of our last list:

> 1 - To be honest, I did not get the version, but the propertiers says it
was created in 02/01/2017, and I downloaded from github two weeks ago;

The current FloWave.US download from Github is version 0.2.1, which was released on July 22, 2016. As a future reference, you can locate the code version number and release date from the [Release page](https://github.com/ccoolbaugh/FloWave.US/releases). It may be helpful to cite the version number if the software is used in a publication. 

> 2 - Yes, I did.

> 3 - Yes, It occurred.

I am concerned that you are getting the same error with the demo videos, and I recommend we troubleshoot with the demo videos and the provided Ultrasound Screen Capture Settings file (GELogiqBookeDefault.mat) before moving on to your custom application. 

In your initial issue, you mentioned: 
> In this part, Distance Scale Position is only displaying for me, neither red or green. 

When you run `FloWaveUS.m` in Matlab, you should see only a red cursor. The multiple colors (red, green, yellow) are only an option when you run `UsSetup.m`. 

The red cursor is visible to help you click on the ranges displayed in the velocity, distance, and time scales in a Pulse Wave ultrasound screen capture. You click on two points on the figure to calibrate the pixel information in the screen capture to the units you are measuring (e.g. cm/s or cm). 

I apologize if this is redundant to what you have already done, but I recommend following along with the [FloWave.US tutorials](https://github.com/ccoolbaugh/FloWave.US/wiki/4.-How-to-Use-FloWave.US) while you analyze the DemoMuscleContraction.mov video. You will need to use the GELogiqBookeDefault.mat ultrasound screen capture settings file. Hopefully, the tutorial has some some additional tips and videos to work through the problem.

If you continue to get the error, it may be a problem with the version of MATLAB you are using. FloWave.US requires version R2011b or newer to run properly. 

Let me know how it goes, and we'll try to figure out the problem. 

Crystal

**Comment by britolc** [comment]
Hi Crystal,

It is me again,
I did with your demo video. In the FloWave, after to put the time scale the
following error appear on the Command Window

Undefined function or variable 'PWy'.
Error in FloWaveUS (line 84)
ROI(:,:,:) = OneFrame(PWy(1):PWy(2), PWx(1):PWx(2),:);

This is the same error when I use my own videos.

Sorry for disturbing you again.
Thank you so much for your time.
att

Leandro

2017-03-22 10:19 GMT-07:00 Crystal Coolbaugh <notifications@github.com>:

**Comment by ccoolbaugh** [comment]
Hi Leandro,

As I mentioned before, it is curious to me that you are receiving this error message with the demo videos and the default Ultrasound Screen capture settings. These videos and files have been independently tested by over 100 users without this error. Therefore, I am wondering if you may have accidentally modified the Ultrasound Screen capture settings file after you downloaded it from GitHub. 

Before we figure out why you are getting the error, let's look at what the error message means: 
> Undefined function or variable 'PWy'

Matlab stops because it calls the variable 'PWy', but the variable does not exist or has not been defined.  

PWx and PWy are variables created in the Ultrasound Screen Capture Settings Program (UsSetup.m). These variables define the x and y screen coordinates of the pulse wave spectrum in the image of the ultrasound screen. 

These variables are defined in the default ultrasound screen capture settings file (GELogiqBookeDefault.mat) so this error should not occur if you use the default file included in the Github download. 

We can test if you have these variables defined in the default ultrasound screen capture settings by doing the following: 

1. Open Matlab and change the current folder to the folder containing the default screen capture settings. 
2. Type the following into the command prompt (hit enter after each line):
`load GELogiqBookeDefault.mat`
`PWx`
`PWy`

The PWx and PWy variables should display the following values in the command prompt:
PWx = 27 464
PWy = 274 449

If you do not get these values, then I recommend you download the GELogiqBookeDefault.mat settings file again from GitHub and try to run the demo videos again. 

As a general note, I am happy to help you work with the program and debug errors; however, I would appreciate it if you can provide more information when posting problems. You can upload videos, screen shots, or other documents to the issues page. The more information you provide about the steps taken before the error, the equipment you use, and example files will help me give better advice for your problem. 

Thanks,
Crystal
